### ISSUE TITLE
Thanks for this, can I use center=true in chamferCube ?

### ISSUE THREAD

**Issue by kernelsandoz** [SebiTimeWaster/Chamfers-for-OpenSCAD#4]

**Comment by SebiTimeWaster** [comment]
No, and i dont plan to implement it, it is kind of a useless function unless you are in very specific circumstances. 

But this is not a problem, just use this module:

```
module chamferCubeCenter(size) {
    translate([-size[0] / 2, -size[1] / 2, -size[2] / 2]) chamferCube(size);
}
```

So usage would look like this:

```
include <Chamfers-for-OpenSCAD/Chamfer.scad>;

module chamferCubeCenter(size) {
    translate([-size[0] / 2, -size[1] / 2, -size[2] / 2]) chamferCube(size);
}

chamferCubeCenter([10, 10, 10]);
```

![image](https://user-images.githubusercontent.com/3726309/129028870-f9095310-ea88-444b-a0fe-529a120d41ce.png)

**Comment by kernelsandoz** [comment]
Thanks for the advice.

My specific circumstance for using center=true is "I am stumbling around
trying anything"

A chamfer makes all the difference and will give my cubes with cylinders
punched through them a more professional appearance.

So thanks again for your module (library ?).
